spring.application.name=auth-service
server.port=0
#Eureka
eureka.client.serviceUrl.defaultZone=http://${discovery.host}:${discovery.port}/eureka/
#Spring JPA
spring.datasource.url=jdbc:postgresql://${auth.datasource.host}:${auth.datasource.port}/${auth.datasource.database}
spring.datasource.username=${auth.datasource.username}
spring.datasource.password=${auth.datasource.password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Logging
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.crm.auth=DEBUG
#RabbitMQ
spring.rabbitmq.host=${rabbit.host}
spring.rabbitmq.port=${rabbit.port}
spring.rabbitmq.username=${rabbit.username}
spring.rabbitmq.password=${rabbit.password}
#Redis
spring.data.redis.host=${redis.host}
spring.data.redis.port=${redis.port}
spring.data.redis.user=${redis.username}
spring.data.redis.password=${redis.password}
#App properties
app.token.signing.key=${auth.token.signing.key}
app.refresh-token.expiration=7200
app.refresh-token.length=50
app.token.expiration=30
app.password.length=15
#In seconds. 36000 seconds = 10 hours
app.redis.user-permission.ttl=36000