spring.application.name=auth-service
server.port=0
#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#Spring JPA
spring.datasource.url=jdbc:postgresql://localhost:5433/AuthDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Logging
logging.level.sql=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.crm.auth=DEBUG
#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=aappaa
spring.rabbitmq.password=aappaapass
#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis_password
spring.data.redis.user=redis_user
#App properties
app.token.signing.key=22ix7nqfcpy76nc42wlu99pk1mu7iwt2q5h7kf6dqwnvhzopvv22ix7nqfcpy76nc42wlu99pk1mu7iwt2q5h7kf6dqwnvhzopvv
app.refresh-token.expiration=7200
app.refresh-token.length=50
app.token.expiration=30
app.password.length=15
#In seconds. 36000 seconds = 10 hours
app.redis.user-permission.ttl=36000